### ISSUE TITLE
Build number is not a number

### ISSUE THREAD

**Issue by XhmikosR** [coverallsapp/github-action#10]
It seems when using this action the build number isn't incremented. Instead it has a random ID like this: https://coveralls.io/builds/26037795

**Comment by lpinca** [comment]
It's the commit sha as per https://github.com/coverallsapp/github-action/blob/8d2940685b011d380ca033e2786e92812f915b1d/src/run.ts#L39-L45.

**Comment by XhmikosR** [comment]
Yeah I noticed too, but that's not a number like it was before

**Comment by nickmerwin** [comment]
Hi all, this is updated now to use `GITHUB_RUN_ID`.
