### ISSUE TITLE
Add support for xml coverage files

### ISSUE THREAD

**Issue by stereomon** [coverallsapp/github-action#107]
https://github.com/coverallsapp/github-action/issues/15
https://github.com/coverallsapp/github-action/issues/22
https://github.com/coverallsapp/github-action/issues/30

All issues from above are not closed and only outline workarounds. There is still no XML support.

Can someone please add XML support to this GitHub action? Are there any plans to add XML support or is this project not meant to be used by standard XML coverage users?

**Comment by nickdnk** [comment]
Just ran into this problem as well.

**Comment by mrexox** [comment]
`v2` version of this action support Cobertura and JaCoCo XML formats. Feel free to request more formats in this project: https://github.com/coverallsapp/coverage-reporter.
