### ISSUE TITLE
Add tags like `v1` etc

### ISSUE THREAD

**Issue by XhmikosR** [coverallsapp/github-action#11]
Many official GitHub Actions follow this scheme. This allows people to have better control on the action. Using `master` can break at any time, while using a tag shouldn't break without updating the major version.

For example https://github.com/actions/setup-node/releases or https://github.com/actions/checkout/releases

BTW I'm not sure how they automate the release process, but I can't imagine this is done by hand, i.e. recreating the tag manually.

**Comment by XhmikosR** [comment]
BTW I'm not sure how they automate the release process, but I can't imagine this is done by hand, i.e. recreating the tag manually.

**Comment by s-weigand** [comment]
To automate it you can use [this action](https://github.com/technote-space/release-github-actions).

**Comment by cedx** [comment]
Just as a reference:
https://docs.github.com/en/actions/creating-actions/about-actions#using-tags-for-release-management

**Comment by hartwork** [comment]
Looking at https://github.com/coverallsapp/github-action/releases now, it seems that there are Git tags and then maybe this ticket can be closed as fixed?

**Comment by XhmikosR** [comment]
Nope, there is no `v1` tag. The idea is to give people the ability to point to a major version tag without having to update their workflows for each minor/patch version.

**Comment by hartwork** [comment]
> Nope, there is no `v1` tag. The idea is to give people the ability to point to a major version tag without having to update their workflows for each minor/patch version.

Maybe we're talking about two different things. If you look at https://github.com/actions/setup-python/tags , they have both `v1` and `v2` Git tags, where `v2` is moved every now and then. It's not something I would do and recommend personally, but it's a workaround that is in use in the wild, and that repository is proof (and not the only one).

**Comment by XhmikosR** [comment]
We are talking about the same thing. This action here does not publish semver major tags on each mino/patch release, which is exactly what this issue is about.

**Comment by mrexox** [comment]
Hey! Now there is a `v1` tag. Please mention me if you feel a need for minor tags like `v1.1` and `v1.2`

**Comment by XhmikosR** [comment]
@mrexox thanks for this! That being said, the process should be automated so that v1, v2 tags are created automatically.
