### ISSUE TITLE
Merge reports for parallel builds

### ISSUE THREAD

**Issue by lpinca** [coverallsapp/github-action#13]
I'm using this action on a matrix based build https://github.com/websockets/ws/blob/use/github-actions/.github/workflows/ci.yml.

I've defined a `test` job which is run in parallel and in this job I run the action with the `parallel` option set to `true`.

https://github.com/websockets/ws/blob/use/github-actions/.github/workflows/ci.yml#L30

I've also defined a `coverage` job which is run after all `test` jobs complete. In this job I run the action with the `parallel-finished` option set to `true`.

https://github.com/websockets/ws/blob/use/github-actions/.github/workflows/ci.yml#L38

This works well but it seems results are not aggregated. Am I doing something wrong?

**Comment by rfgamaral** [comment]
Are you sure this is even working for you @lpinca ?

I've tried the same approach and did some testing:

![image](https://user-images.githubusercontent.com/96476/67679077-27c71780-f980-11e9-8beb-772458ecda26.png)

Every jobs runs on their own container without access to the previous jobs files (unless you use the upload/download artifact actions). So, where is the `parallel-finished=true` action getting the `./coverage/lcov.info` from?

**Comment by lpinca** [comment]
From my understanding the "finished" job does not need any coverage info, it is only used to signal that no more builds for the specific PR/commit will be run.

**Comment by rfgamaral** [comment]
> 
> 
> From my understanding the "finished" job does not need any coverage info, it is only used to signal that no more builds for the specific PR/commit will be run.

Ok, that makes sense. But how are you reaching this conclusion:

> but it seems results are not aggregated

What makes you think the results are note aggregated?

**Comment by lpinca** [comment]
> What makes you think the results are note aggregated?

I see it in the Coveralls web app. Lines that should be covered due to aggregation of results, are not covered. Furthermore the final coverage percentage I get when running this action is smaller than the percentage I get when running on Travis CI where aggregation works.

**Comment by rfgamaral** [comment]
Ok, I see... What's confusing me is, why are you expecting coverage to be different between node versions and thus expect code coverage to be aggregated? In other words, shouldn't coverage results be exactly the same independently of the Node version the tests are running one? In which scenario does this not happen?

**Comment by lpinca** [comment]
It depends... there might be branches that are only executed on a specific version of Node.js like this https://github.com/websockets/ws/blob/7.2.0/lib/permessage-deflate.js#L432-L440 or error handlers that are only run when a specific error is raised and that error is raised only on a particular OS like Windows.

**Comment by rfgamaral** [comment]
Interesting. Thanks for the clarification as I was trying to understand how could this affect my own projects and I wasn't seeing a use case where coverage would be different. Thanks :)

**Comment by novascreen** [comment]
I'm trying to use this in a monorepo with currently 2 reports being uploaded, the second one always seems to override the first one even though the first one logs a URL to a job it no longer exists once the second one is up. `parallel` is `true` and i see `Job ... .1` and `Job ... .2` in the `message` in the debug logs

**Comment by jlabeit** [comment]
I think the environment variable `COVERALLS_SERVICE_NUMBER` needs to be set to a unique identifier so that coverage in the parallel builds can be aggregated correctly.

**Comment by nickmerwin** [comment]
Hi all, we've just released a new version with better parallel support and updated the example configuration in the README:

https://github.com/marketplace/actions/coveralls-github-action#complete-parallel-job-example

**Comment by lpinca** [comment]
@nickmerwin it seems to work well on `push` but not on `pull_request`. See https://coveralls.io/builds/30259246 (push) and https://coveralls.io/builds/30259321 (pull request).

Config is here: https://github.com/websockets/ws/blob/use/github-actions/.github/workflows/ci.yml

**Comment by nickmerwin** [comment]
@lpinca to clarify, you're saying it didn't work on the PR because the coverage fell when it shouldn't have, right?

**Comment by lpinca** [comment]
Yes, and not only that. The job names are incorrect in https://coveralls.io/builds/30259321 (pull request) and correct in https://coveralls.io/builds/30259246 (push). It seems that the `flag-name` option does not work as expected for PRs?

**Comment by nickmerwin** [comment]
@lpinca ok, we've deployed an update that should fix this issue. Could you please trigger another build?

**Comment by lpinca** [comment]
@nickmerwin it seems to work now. Thank you.

I noticed a minor nit:

- On push the job names have the following form `${flag-name} - ${GITHUB_RUN_ID}.${n}` where `n` is an integer that starts from 1 and is incremented for each job.
- On pull request the job name has the same form but `n` is not incremented. It is fixed to 1 so job names have the following format `${flag-name} - ${GITHUB_RUN_ID}.1`.

All job names are still unique and it doesn't seem to cause issues in practice.

**Comment by nickmerwin** [comment]
@lpinca good catch, we've deployed an update that should fix those Job numbers moving forward.

Thanks!
