### ISSUE TITLE
Coveralls not finding repository, response 422 when trying to upload reports

### ISSUE THREAD

**Issue by joaocasarin** [coverallsapp/github-action#134]
I have just configured [this repo](https://github.com/joaocasarin/express-k8s-sqs/) to use coveralls actions as a coverage badge, created the secret as in the image below:
![image](https://user-images.githubusercontent.com/48847394/195901732-353edcbc-82ab-48b5-a07d-eaf8f6839eba.png)

And as you can see [in here](https://github.com/joaocasarin/express-k8s-sqs/blob/main/.github/workflows/ci.yml#L57), I am using the correct secret.

However, everytime I run this job I get the response `Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}`

I have no idea what to do. I already checked in the coveralls website and the repo is fine...

**Comment by joaocasarin** [comment]
The same error happens if I try using `v1.1.2`:

![image](https://user-images.githubusercontent.com/48847394/195939100-bc6c7525-4607-4016-9a97-d398d46f189d.png)

**Comment by vmenger** [comment]
This action doesn't use the coveralls secret, but rather literally this: 

```
github-token: ${{ secrets.GITHUB_TOKEN }}
```

Took me a while too to figure it out. Just copy-paste this literally in your ci.yml.

See:

**Comment by joaocasarin** [comment]
> This action doesn't use the coveralls secret, but rather literally this:
> 
> ```
> github-token: ${{ secrets.GITHUB_TOKEN }}
> ```
> 
> Took me a while too to figure it out. Just copy-paste this literally in your ci.yml.
> 
> See: [lemurheavy/coveralls-public#1627](https://github.com/lemurheavy/coveralls-public/issues/1627)

WOW! that was exactly the issue, their docs is not that clear, but now I get it... Thanks for sharing both the info and another issue that was raised regarding this.

Thanks, my friend!
