### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by Apollon77** [coverallsapp/github-action#135]
We get some warnings on GitHub when using the action (master version):

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by gabririgo** [comment]
also this warning is produced:
`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: coverallsapp/github-action`

**Comment by robsonpeixoto** [comment]
The PR https://github.com/coverallsapp/github-action/pull/139 address it

**Comment by mrexox** [comment]
Hey! In a new `@v1.2.1` and `@v1` (and also `@master`) versions this is fixed. Please, upgrade!
