### ISSUE TITLE
Couldn't find a repository matching this job

### ISSUE THREAD

**Issue by limonte** [coverallsapp/github-action#14]
My config: https://github.com/sweetalert2/sweetalert2/blob/master/.github/workflows/ci.yml#L35-L38

I am sure that the `GH_TOKEN` secret is present in the repo because `semantic-release` is using it as well (successfully).

Here's the build with failure: https://github.com/sweetalert2/sweetalert2/runs/262138044

> Run coverallsapp/github-action@master
> Using lcov file: ./coverage/lcov.info
> ##[error]Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
> ##[error]Node run failed with exit code 1

**Comment by nickmerwin** [comment]
Hi @limonte the line:

```yaml
github-token: ${{ secrets.GH_TOKEN }}
```

Needs to be exactly:
```yaml
github-token: ${{ secrets.GITHUB_TOKEN }}
```

It's a special environment variable that you don't need to manually set up in your secrets section. 

More info: https://help.github.com/en/articles/virtual-environments-for-github-actions#github_token-secret
