### ISSUE TITLE
Carryforward flag support

### ISSUE THREAD

**Issue by EvHaus** [coverallsapp/github-action#142]
Hey team. I'm excited about the new [Carryforward Flag feature](https://coveralls.io/better-monorepo-support) announcement. I'm curious if it's something I can use today with this GitHub Action. The instructions say to modify the "Close Parallel Build Webhook" but I'm not sure what this is. We only use the GitHub Action to submit coverage results from our CI to Coveralls. Is there some additional step I need to add to get monorepo support working? (I've already set the "LAYOUT TYPE" of our repo to "monorepo" in Coveralls).

Thanks for your help!

**Comment by afinetooth** [comment]
Hi @EvHaus,

We got your support request about this to support@coveralls.io, available to all paid users, so we will respond there.

Thanks,
James

**Comment by mrexox** [comment]
Hey! Now the action supports carryforward flags feature. Please, use `coverallsapp/github-action@v1` or `coverallsapp/github-action@master`
