### ISSUE TITLE
V2 Error: <File::NotFoundError:Error opening file with mode 'r':>

### ISSUE THREAD

**Issue by bcomnes** [coverallsapp/github-action#155]
Just got a coveralls PR to update the action on one of my repos, but it failed with an error I haven't seen before:

https://github.com/hifiwi-fi/bc-bookmarklet/actions/runs/4347073586/jobs/7594582616

It looks like it's trying to interpret en esbuild artifact comment as a path, where it shouldn't be.

The action was working great on v1. Let me know if you need any more details or information. The code in this repo is fully open source so it's easy to inspect.

**Comment by mrexox** [comment]
Thank you for the issue. I noticed that the content of `lcov.info` is the following

```
TN:
SF:dist/<define:DATA>
FNF:0
FNH:0
DA:1,1
LF:1
LH:1
BRF:0
BRH:0
end_of_record
TN:
SF:scripts/wrapper.js
FN:1,getBookmarklet
FNF:1
FNH:1
FNDA:1,getBookmarklet
DA:1,1
DA:2,1
DA:3,1
DA:4,2
DA:5,2
DA:6,1
DA:7,1
DA:8,1
LF:8
LH:8
BRDA:1,0,0,1
BRDA:3,1,0,2
BRF:2
BRH:2
end_of_record
```

Looks like we try to read `dist/<define:DATA>` file which obviously does not exist. I'll fix it with the next release candidate.

**Comment by mrexox** [comment]
Hi @bcomnes! The fix was just released for the coverage reporter. You can just re-run your workflow and it should be successful.
