### ISSUE TITLE
jacoco doesn't work

### ISSUE THREAD

**Issue by ortex** [coverallsapp/github-action#160]
related to https://github.com/coverallsapp/github-action/issues/22

action: https://github.com/roc-streaming/roc-java/actions/runs/4589393860/jobs/8104254169

workflow: https://github.com/roc-streaming/roc-java/pull/67

jacocoTestReport.xml valid and works fine with codecov https://app.codecov.io/gh/roc-streaming/roc-java/tree/jacoco-ci/src

but fails with coveralls:

```
✏️ Forced coverage format: jacoco
📄 Using coverage file: /home/runner/work/roc-java/roc-java/build/reports/jacoco/test/jacocoTestReport.xml
#<Enumerable::EmptyError:Empty enumerable>
Error: Process completed with exit code 1.
```

Just in case, locally generated jacocoTestReport.xml from the same branch
[jacocoTestReport.txt](https://github.com/coverallsapp/github-action/files/11132630/jacocoTestReport.txt)

**Comment by mrexox** [comment]
Hey! Thank you for the issue. It was the problem with parsing, and now it should be fixed. If you retry the workflow, everything should work fine.

Feel free to reopen the issue if the bug persists or you see any other issues.

**Comment by ortex** [comment]
Thanks!
