### ISSUE TITLE
Source not available for Windows paths ( \ )

### ISSUE THREAD

**Issue by luttje** [coverallsapp/github-action#162]
Hi there, 

First of all thanks for this great service to (open-source) projects, much appreciated!

I've run into a problem with paths on Coveralls: When using [coverlet for a .NET project](https://github.com/coverlet-coverage/coverlet/blob/d93613826b1a33f894b9c80f6ae893643a8b7254/src/coverlet.core/Reporters/LcovReporter.cs#L37), paths on Windows get saved in the `.lcov` file as is. For example: `C:\...etc...\Key2Joy\Output.cs`. This becomes a problem when [the coveralls github-action](https://github.com/coverallsapp/github-action/blob/66741573064b23a82206aebd518f4bb11802fa5a/src/lcov-processor.ts#L11) [sends](https://github.com/coverallsapp/github-action/blob/66741573064b23a82206aebd518f4bb11802fa5a/src/run.ts#L108) the path like that ([my workflow](https://github.com/luttje/Key2Joy/blob/789b7b79b7cdb6b190110abdf34887cb0c71ab87/.github/workflows/tests.yml#L20)). Because although the file will be listed on Coveralls (with correct coverage information), [Coveralls isn't able to link](https://coveralls.io/builds/58613375/source?filename=%5CKey2Joy%5COutput.cs) to the repo source, even though [it is there](https://github.com/luttje/Key2Joy/blob/789b7b79b7cdb6b190110abdf34887cb0c71ab87/Key2Joy/Output.cs)

![image](https://user-images.githubusercontent.com/2738114/230290426-c56c4316-68dd-4a8a-89a6-e02f1ed7fb51.png)

If Windows-style paths are not valid according to some LCOV standard, then I guess I should report this in the coverlet repo. Though I'm having trouble finding exact specifications on the LCOV format. Or perhaps this github action isn't the right place, but Coveralls website support is, since other Coveralls integrations may also have this problem?

Would be happy to hear some thoughts on where the problem should be reported, or if some feature exists to translate these paths (and I've completely missed it).

Thanks in advance!

**Comment by mrexox** [comment]
Hey! The problem was just resolved for this issue: https://github.com/coverallsapp/coverage-reporter/issues/44. New coverage-reporter should be available for github action v2. Please, rerun the workflow which had this problem. Will be waiting for your feedback :pray:

**Comment by luttje** [comment]
I had missed that issue. Replying to confirm that it works great now.

Thanks for the swift response! ✌
