### ISSUE TITLE
Doesn't seem to work when tests not ran from root directory

### ISSUE THREAD

**Issue by NullVoxPopuli** [coverallsapp/github-action#17]
I use a mono repo, and I've been trying a bunch of test coverage services. Most have an add prefix command that allows me to specify my project's location within the monorepo. 

Here is my coverage report (empty): 
https://coveralls.io/github/NullVoxPopuli/emberclear

And the build:
https://github.com/NullVoxPopuli/emberclear/commit/f28cffb74a10fd26fbc733351a3c4054f41abaa0/checks?check_suite_id=282980627

And the generated HTML report that I publish with the deploy:
https://emberclear.io/coverage/index.html

And the code I want reporting on lives here: https://github.com/NullVoxPopuli/emberclear/tree/master/packages/frontend

**Comment by Bnaya** [comment]
@NullVoxPopuli  see https://github.com/coverallsapp/github-action/issues/21#issuecomment-552217207

**Comment by NullVoxPopuli** [comment]
Because I was trying _every coverage service_, I just decided to give up on the service providing mono repo support, and learn how to modify the lcov report myself.

for others: https://github.com/NullVoxPopuli/emberclear/blob/master/packages/frontend/scripts/test-with-coverage.sh#L13

and in case I move that file:

```bash
#!/bin/bash
# 
# $CWD == <repo-root>/packages/frontend

export GIT_COMMIT_SHA=$GITHUB_SHA
export GIT_BRANCH=${GITHUB_REF#refs/heads/}
export COVERAGE=true

time yarn test

exit_code=$?

# fix the paths, since we aren't generating coverage from
# the root of the mono repo
sed -i -E "s/^SF:(.+)$/SF:packages\/frontend\/\1/" coverage/lcov.info
echo "Successfully fixed the test coverage paths!"

exit $exit_code
```

**Comment by NoxHarmonium** [comment]
@NullVoxPopuli Thanks for the `sed` one-liner, it worked great in my monorepo.
I wonder if we could fix this by adding a "base-path" property to the action.

I'll have a look and see if I can raise a PR.
