### ISSUE TITLE
Ability to select version of coverage-reporter

### ISSUE THREAD

**Issue by ogenstad** [coverallsapp/github-action#170]
Yesterday our CI started to see failures after the release of coverage-reporter v0.3.8 as reported in that repo [here](https://github.com/coverallsapp/coverage-reporter/issues/65), looking through the repo it seems that v0.3.7 resulted in failures of [other pipelines](https://github.com/coverallsapp/coverage-reporter/issues/64)

By default for at least Windows and Mac the v2 version of this action downloads either https://github.com/coverallsapp/coverage-reporter/releases/latest/download/coveralls-linux.tar.gz or https://github.com/coverallsapp/coverage-reporter/releases/latest/download/coveralls-windows.zip.

It would be nice if it was possible to pin the version of coverage-reporter that this action would use to ensure that the pipelines can continue to work if bugs are introduced to future versions of coverage-reporter.

**Comment by afinetooth** [comment]
@ogenstad Agree this would be a very helpful option. Have added it to our backlog for more consideration. Thanks.

**Comment by ogenstad** [comment]
Is there any update on this? After https://github.com/coverallsapp/coverage-reporter/releases/tag/v0.6.8 was released our pipelines have started to fail with:

```
Run coverallsapp/github-action@v2
Run mkdir -p ~/bin/
coveralls-linux.tar.gz: OK
Run coveralls report        
 
⠀⠀⠀⠀⠀⠀⣿
⠀⠀⠀⠀⠀⣼⣿⣧⠀⠀⠀⠀⠀⠀⠀ ⣠⣶⣾⣿⡇⢀⣴⣾⣿⣷⣆ ⣿⣿⠀⣰⣿⡟⢸⣿⣿⣿⡇ ⣿⣿⣿⣷⣦⠀⠀⢠⣿⣿⣿⠀⠀⣿⣿⠁⠀⣼⣿⡇⠀⢀⣴⣾⣿⡷
⠶⣶⣶⣶⣾⣿⣿⣿⣷⣶⣶⣶⠶  ⣸⣿⡟ ⠀⢠⣿⣿⠃⠈⣿⣿⠀⣿⣿⢠⣿⡿⠀⣿⣿⣧⣤⠀⢸⣿⡇⣠⣿⡿⠀⢠⣿⡟⣿⣿⠀⢸⣿⡿⠀⠀⣿⣿⠃⠀⢸⣿⣧⣄
⠀⠀⠙⢻⣿⣿⣿⣿⣿⡟⠋⠁⠀⠀ ⣿⣿⡇⠀ ⢸⣿⣿⠀⣸⣿⡟⠀⣿⣿⣾⡿⠁ ⣿⣿⠛⠛⠀⣿⣿⢿⣿⣏⠀⢀⣿⣿⣁⣿⣿⠀⣾⣿⡇⠀⢸⣿⡿⠀⠀⡀⠙⣿⣿⡆
⠀⠀⢠⣿⣿⣿⠿⣿⣿⣿⡄⠀⠀⠀ ⠙⢿⣿⣿⠇⠈⠿⣿⣿⡿⠋⠀⠀⢿⣿⡿⠁⠀⢸⣿⣿⣿⡇⢸⣿⣿⠀⣿⣿⣄⣾⣿⠛⠛⣿⣿⢠⣿⣿⣿ ⣼⣿⣿⣿ ⣿⣿⡿⠋⠀
⠀⢀⣾⠟⠋⠀⠀⠀⠙⠻⣷⡀⠀⠀
 
  v0.6.8

🔍 Detected coverage file: coverage.xml
🔍 Detected coverage file: .coverage
#<CoverageReporter::CoveragepyParser::ParserError:--: 1: coverage: not found
>
```

**Comment by afinetooth** [comment]
@ogenstad sorry for the delay and thank you for opening https://github.com/coverallsapp/coverage-reporter/issues/119.

This goes in the hopper this week, along with the same ability in our other CI extension (CircleCI Orb).

I'll post updates here, and [here](https://github.com/coverallsapp/orb/issues/42).

**Comment by afinetooth** [comment]
@ogenstad wanted to let you know that we cut a new release of the [Coveralls GitHub Action](https://github.com/marketplace/actions/coveralls-github-action) ([`v2.3.0`](https://github.com/coverallsapp/github-action/releases/tag/v2.3.0)) with new input option to allow pinning the version of [Coverage Reporter](https://github.com/coverallsapp/coverage-reporter).

When you get a chance to use it, please let us know how it works for you.

For those waiting on the same ability in our [CircleCI Orb](https://circleci.com/developer/orbs/orb/coveralls/coveralls), that is WIP. Please give us another week or so.

I'm going to close this. Please re-open if any issues.
