### ISSUE TITLE
Having Issues Bad Response in GitHub Action CI

### ISSUE THREAD

**Issue by iftekhariasif** [coverallsapp/github-action#180]
I am having the following issue in Github Action. 

```
#!/bin/bash -eo pipefail
goveralls -coverprofile=coverage.txt -service=circle-ci -repotoken=${COVERALLS_REPO_TOKEN}

bad response status from coveralls: 500
{"message":"Build processing error.","error":true,"url":""}

Exited with code exit status 1
CircleCI received exit code 1
```

My local is working fine & seems code has no bug.
Does anyone know the reason? (I am totally clueless)

**Comment by ZLY201** [comment]
I also got the same error.

**Comment by peaceiris** [comment]
I got the error on CircleCI with https://github.com/mattn/goveralls.

This problem looks like an issue related to the coveralls endpoint, not only this action.

**Comment by mrexox** [comment]
Hey! Thank you all for reporting. We had an infrastructural issue but it was fixed by now.

**Comment by afinetooth** [comment]
Thanks all and apologies for the inconvenience. [Incident](https://manage.statuspage.io/pages/3h72wtpg5fqs/incidents/1jsfs39kmwxp).
