### ISSUE TITLE
Lcov file not found

### ISSUE THREAD

**Issue by ibakshay** [coverallsapp/github-action#2]
Hi, 
I tried to use github-action for doing CI/CD jobs in   our application https://github.com/cla-assistant/cla-assistant . However, when performing `coveralls` step in the job, I am running into an issue like `Lcov file not found` https://github.com/ibakshay/cla-assistant/blob/master/.github/workflows/nodejs.yml . We are using `mocha_istanbul` for generating the Lcov file and I can see from the logs that It is generating the file and also the path is correct. Like you have mentioned in the readme file I have also added `secret` in the repository. Because of this, my build keeps failing and I don't know what I am missing. 
![Screen Shot 2019-08-14 at 16 18 13](https://user-images.githubusercontent.com/33329946/63028469-2b81ec80-beaf-11e9-92f1-581c28502300.png)

**Comment by nickmerwin** [comment]
Hi @ibakshay could you try with:

```yaml
        github-token: ${{ secrets.github_token }}
        path-to-lcov: ./output/coverage/lcov.info
```

I've added a leading "/" to the path, to match the output path in your Gruntfile.js.

Also, the `github-token` parameter needs the `secrets.github_token`, which is built into the action and does not need to be specified in your secrets settings.

**Comment by ibakshay** [comment]
Wow I spent a day in trying to solve this issue . It is working perfectly now. Like you pointed out, 
I have missed the leading "/" to the path and I changed to `secrets.github_token`. Thank you very much once again and I will implement in our prod instance soon 😊.

`secrets.github_token` was little confusing for me at first and I feel It will be great for the other users If you can add this point which you told in your reply to the readme file 😊.
> the github-token parameter needs the secrets.github_token, which is built into the action and does not need to be specified in your secrets settings.

**Comment by nickmerwin** [comment]
@ibakshay great to hear it! I've added that extra note to the README. Closing the issue for now.

**Comment by sergey19941201** [comment]
My teammate has resolved this issue adding `coverlet.msbuild` package to project with tests. After that it started to work and file was found
