### ISSUE TITLE
basic setup creates empty entry

### ISSUE THREAD

**Issue by Bnaya** [coverallsapp/github-action#21]
similar to #17, but not monorepo

See the following action run:
https://github.com/Bnaya/objectbuffer/commit/c42aeb97d855dc18c67278d0abbefeefee4d1951/checks?check_suite_id=304075414
there's `cat ./coverage/lcov.info` before the coverage upload action to show that the file is ok.
The created coverall job is: https://coveralls.io/jobs/55487739
and its simply empty.

**Comment by Bnaya** [comment]
Some finding, you can set env NODE_COVERALLS_DEBUG: 1 to get debug mode

**Comment by Bnaya** [comment]
So the issue was, i was using https://github.com/Borales/actions-yarn
And it runs yarn inside docker
so the paths inside the lcov file were docker file system paths.
node-coveralls just ignored them, without any warning

**Comment by joaqcid** [comment]
@Bnaya how did you fix it? you have to copy the files out of yanr docker?
