### ISSUE TITLE
Support GitHub Actions ARM runners

### ISSUE THREAD

**Issue by aaomidi** [coverallsapp/github-action#218]
```
/home/runner/work/_temp/b1d5f4e4-9e42-492a-b074-ae4e66c473a0.sh: line 1: /home/runner/bin/coveralls: cannot execute binary file: Exec format error
```

**Comment by afinetooth** [comment]
@aaomidi We are working on this right now and hope to deliver that support this week.

You can track the issue in [this issue](https://github.com/coverallsapp/coverage-reporter/issues/137) ([coverage-reporter #137](https://github.com/coverallsapp/coverage-reporter/issues/137)) on our repo for the GitHub Actions's underlying executable, [coverage-reporter](https://github.com/coverallsapp/coverage-reporter). That is the executable that needs the ARM64 support.

We have had more trouble than expected with this, so if not this week, we would hope to resolve by next week sometime.

**Comment by SpayDolf** [comment]
![image](https://github.com/user-attachments/assets/56d9b53d-8d25-4c78-adc5-96dd4264357c)

**Comment by afinetooth** [comment]
@SpayDolf, apparently because you are "a participant" (aka. following the issue):

<img width="1392" alt="Screenshot 2024-08-16 at 8 47 50 AM" src="https://github.com/user-attachments/assets/f1587d0f-b4f6-4066-883a-29ae5de7f4e7">

I don't know how it happened---neither I nor @aaomidi can follow for you, and I don't see that either of us mentioned you in a comment. 

But all you need to do to stop receiving notifications for this issue is remove yourself / unfollow, or unsubscribe:

<img width="320" alt="Screenshot 2024-08-16 at 8 52 16 AM" src="https://github.com/user-attachments/assets/e65d2e51-6724-4beb-b805-f908652e9a5b">

**Comment by SpayDolf** [comment]
I think my device is being controlled remotely

**Comment by afinetooth** [comment]
Mine also has a mind of its own.

**Comment by SpayDolf** [comment]
![image](https://github.com/user-attachments/assets/50429bfb-38a4-4e8f-96e8-0b0d9a01dc49)

**Comment by SpayDolf** [comment]
![image](https://github.com/user-attachments/assets/2bab70cf-d59b-4481-a121-b85d598809c6)

**Comment by SpayDolf** [comment]
Wtf is this lol I don't even own a watch

**Comment by aaomidi** [comment]
Did this get resolved? I see that the binary is now being built for ARM too?

**Comment by afinetooth** [comment]
Hi @aaomidi. Not quite yet. But we're close.

We've tried to cut a release with `arm64` binaries twice now that we've pulled for issues discovered after the fact, so we are now adding more verification steps into our CI/CD process.

We genuinely hope to have it out today, but if not, then by Mon.

**Comment by OJFord** [comment]
@afinetooth Will we need to change anything to use it, or will it just start working, automatically using the right binary for an existing `uses: coverallsapp/githubaction@v2`?

**Comment by afinetooth** [comment]
Hi @OJFord. We plan to release three (3) specific changes in this order and timeframe:

1. **This week** - We'll cut a [new release of coverage-reporter](https://github.com/coverallsapp/coverage-reporter/releases) itself, which will include a new linux binary for `aarch64` and provide instructions in its README for how to install and run that version.
2. **This week or next week** - We'll cut new releases of our [github-action](https://github.com/coverallsapp/github-action) and [orb](https://github.com/coverallsapp/orb) with new input options to specify which version of coverage-reporter to use.
3. **Next 4-6 weeks** - We'll cut new releases of our [github-action](https://github.com/coverallsapp/github-action) and [orb](https://github.com/coverallsapp/orb) that will automatically select the right version of coverage-reporter based on both runner OS and architecture (If possible. We have not validated this yet.)

**Comment by afinetooth** [comment]
@aaomidi @OJFord 

Wanted to let you know that we [released `v0.6.15` of coverage-reporter](https://github.com/coverallsapp/coverage-reporter/releases), which includes a statically-compiled binary for Linux (aarch64).

You can **download & install the `aarch64` version like this**:

```
curl -L https://coveralls.io/coveralls-linux-aarch64.tar.gz | tar -xz -C /usr/local/bin
```

### Usage: 

No differences in using this version outside of downloading the correct `tar.gz` archive:

1. **Download & install the correct archive**: Follow the same [install instructions for Linux](https://github.com/coverallsapp/coverage-reporter?tab=readme-ov-file#linux) that you'll find in the **coverage-reporter README**, just use the appropriate filename, which you can find in these [release assets](https://github.com/coverallsapp/coverage-reporter/releases/tag/v0.6.15).
2. **Use as normal after installation**: All `.tar.gz` [archives](https://github.com/coverallsapp/coverage-reporter/releases/tag/v0.6.15) in all releases, regardless of filename, will un-tar as a binary named `coveralls` so the binary is ready receive the commands covered in the standard [usage instructions](https://github.com/coverallsapp/coverage-reporter?tab=readme-ov-file#usage).

### Usage for [Coveralls GitHub Action](https://github.com/coverallsapp/github-action) (Coming Soon)

- **Currently unavailable:** 
    - Working on it next. Until then, some notes:
        - When [`runner.os == 'Linux'`](https://github.com/coverallsapp/github-action/blob/643bc377ffa44ace6394b2b5d0d3950076de9f63/action.yml#L93-L112), the github-action currently [retrieves `coveralls-linux`](https://github.com/coverallsapp/github-action/blob/643bc377ffa44ace6394b2b5d0d3950076de9f63/action.yml#L107), a generically named binary that represents the `x84-64` version.
        - The currently available [input option `coverage-reporter-version`](https://github.com/marketplace/actions/coveralls-github-action#:~:text=coverage%2Dreporter%2Dversion) will _not_ specify `platform/architecture`, only `release-number` (ie. `v0.6.15`).
        - We'll be releasing a **new input option for `platform/architecture`**, which, for now, will only apply when `runner.os = 'Linux'` and will take as input, either: [`x86_64` (default) | `aarch64`]

**Comment by aaomidi** [comment]
Woot! Thank you for your hard work here :)

**Comment by afinetooth** [comment]
@aaomidi thanks. 

And thanks for your patience. We'll get the new input option for the github-action out as soon as we can.

**Comment by afinetooth** [comment]
@aaomidi [release `v2.3.4` of the `github-action`](https://github.com/coverallsapp/github-action/releases/tag/v2.3.4) now supports the `coverage-reporter-platform` input option, with values of [`x86_64` | `aarch64` (or `arm64`)].

Please let me know if you have any issues. 

BTW, you can access the latest version of the `github-action` (in this case `v2.3.4`) simply by continuing to use `coverallsapp/github-action@v2` in your workflows.

**Comment by fredden** [comment]
https://github.com/coverallsapp/github-action/pull/238 should remove the need for consumers of this action to make any changes at their end.

**Comment by afinetooth** [comment]
> [#238](https://github.com/coverallsapp/github-action/pull/238) should remove the need for consumers of this action to make any changes at their end.

[release `v2.3.6` of the `github-action`](https://github.com/coverallsapp/github-action/releases/tag/v2.3.6) now auto-detects `coverage-reporter-platform` from environment (but `coverage-reporter-platform` can still be set explicitly).

Thanks to @fredden and @jrfnl. 🙏
