### ISSUE TITLE
Coveralls: command not found

### ISSUE THREAD

**Issue by mfrr1118** [coverallsapp/github-action#219]
Today this ation started failing with the following error:

```
coveralls: command not found
```

No changes have been recently done on our end. It's failing for all of our projects.

Please see screenshot for more context
<img width="1011" alt="image" src="https://github.com/user-attachments/assets/1aa7f9fc-66f2-4cc7-882e-d1c9283084dd">

**Comment by sajith** [comment]
This is happening to us too. Here's an example: https://github.com/atlanticwave-sdx/sdx-controller/actions/runs/10494639925/job/29071429737

**Comment by sajith** [comment]
I'm guessing that `~/bin` is no longer in the runner's `PATH`?

**Comment by afinetooth** [comment]
@mfrr1118, @sajith,

@mfrr1118 thanks for the report. We have pulled that latest release of coverage-reporter. We will fix and push again later tonight. 

Please let us know here if your next run doesn't work. It should be with version `0.6.13`.

**Comment by sajith** [comment]
@afinetooth Yes, I see a `v0.6.13` and I see that it works.  Thank you!

**Comment by afinetooth** [comment]
@sajith great, thank you!

**Comment by afinetooth** [comment]
For any new visitors, this issue is **resolved**, but I will leave it open for a while longer for anyone just discovering the error in their build logs today.

**Fix**:
The fix is to simply re-run your CI build. The next run should succeed and the version of coverage reporter shown in the output should be `v0.6.13`

**Comment by mfrr1118** [comment]
It's working for us. Thank you for such quick action on your end
