### ISSUE TITLE
error while loading shared libraries: libevent-2.1.so.7

### ISSUE THREAD

**Issue by mfrr1118** [coverallsapp/github-action#220]
Hi, i am seeing this error when running this action

```
coveralls: error while loading shared libraries: libevent-2.1.so.7: cannot open shared object file: No such file or directory
```

<img width="978" alt="image" src="https://github.com/user-attachments/assets/0176ab31-a220-49a0-88ce-b91bad7dca2b">

**Comment by afinetooth** [comment]
Hi @mfrr1118. We pulled that last release (`v0.6.14`). Please re-run. The action should now grab `v0.6.13` of coverage-reporter.

**Comment by afinetooth** [comment]
@mfrr1118 just checking to make sure re-running fixed your issue.

**Comment by mfrr1118** [comment]
Sorry for the delay. This worked. Thanks for the quick turnaround

**Comment by afinetooth** [comment]
You bet. No worries. Thanks for the update!
