### ISSUE TITLE
Input `coverage-reporter-version` isn't recognized.

### ISSUE THREAD

**Issue by ConsoleCatzirl** [coverallsapp/github-action#225]
Setting [`coverage-reporter-version`](https://github.com/marketplace/actions/coveralls-github-action#:~:text=coverage%2Dreporter%2Dversion,on%20MacOS.) has no effect other than a warning that the input isn't recognized:

```
Warning: Unexpected input(s) 'coverage-reporter-version', valid inputs are ['github-token', 'path-to-lcov', 'file', 'files', 'format', 'flag-name', 'parallel', 'parallel-finished', 'carryforward', 'coveralls-endpoint', 'allow-empty', 'base-path', 'git-branch', 'git-commit', 'compare-ref', 'compare-sha', 'debug', 'measure', 'fail-on-error']
Run coverallsapp/github-action@v[2](https://github.com/Sage-Bionetworks-IT/cfn-explode-macro/actions/runs/11148235826/job/30984406533#step:8:2)
  with:
    coverage-reporter-version: v0.6.14
    file: coverage.lcov
    fail-on-error: false
    github-token: ***
    coveralls-endpoint: https://coveralls.io
    allow-empty: false
    debug: false
    measure: false
  env:
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/Sage-Bionetworks-IT/cfn-explode-macro/actions/runs/11148235826/job/30984406533#step:8:3).9.20/x6[4](https://github.com/Sage-Bionetworks-IT/cfn-explode-macro/actions/runs/11148235826/job/30984406533#step:8:4)
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.9.20/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.20/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.20/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.20/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.20/x64/lib
Run mkdir -p ~/bin/
  mkdir -p ~/bin/
  cd ~/bin/
  curl -sLO https://github.com/coverallsapp/coverage-reporter/releases/latest/download/coveralls-linux.tar.gz
  curl -sLO https://github.com/coverallsapp/coverage-reporter/releases/latest/download/coveralls-checksums.txt
  cat coveralls-checksums.txt | grep coveralls-linux.tar.gz | sha2[5](https://github.com/Sage-Bionetworks-IT/cfn-explode-macro/actions/runs/11148235826/job/30984406533#step:8:5)6sum --check
  tar -xzf coveralls-linux.tar.gz
```

**Comment by afinetooth** [comment]
@jesusaurus Thanks for reporting. Looking into it. Will update you here.

**Comment by afinetooth** [comment]
Hi @jesusaurus.

It looks like that input option is present in the latest version of the [github-action (`v2.3.0`)](https://github.com/coverallsapp/github-action/releases/tag/v2.3.0).. You can see the input defined on [lines 69-72](https://github.com/coverallsapp/github-action/blob/main/action.yml#L69-L72) of the `action.yml` file on `main`.

However per [this conditional](https://github.com/coverallsapp/github-action/blob/main/action.yml#L86-L91), that input option is not available on MacOS runners, so if your runner was MacOS you would see the error message:

```
The coverage-reporter-version parameter is not available on macOS
```

But that's not what you're seeing, so I'm thinking you may be referencing an **older version** of the github-action?

Are you referencing a version older than `v2.3.0` such as?:

```
coverallsapp/github-action@v2.2.3
```

The `@v2` version label should get you the latest version, which is `v2.3.0`:

```
coverallsapp/github-action@v2
```

**Comment by jesusaurus** [comment]
@afinetooth thanks for the quick response, I'm currently using `coverallsapp/github-action@v2`, and thanks for confirming that it pulls the latest 2.x version. This is running on the `ubuntu-latest` Github runner, it looks like the exact version is Ubuntu 22.04.5, I hope that helps.

**Comment by afinetooth** [comment]
@jesusaurus OK, got it. Likewise, thanks for confirming your usage of `@v2`. 

In that case, it does seem like a bug. We'll have a deeper look and I'll get back to you asap.

**Comment by ConsoleCatzirl** [comment]
@afinetooth thanks for looking into this. Still no change when using `coverallsapp/github-action@v2`, so I tried using `coverallsapp/github-action@v2.3.2` explicitly, and that seems to have fixed my issue. I guess the `v2` version isn't being updated.

(P.S. I changed my username)

**Comment by afinetooth** [comment]
@ConsoleCatzirl I think the real underlying issue was this:
https://github.com/coverallsapp/github-action/issues/222

We had fallen out of our standard pattern for releases in this repo and our floating tag `v2` was not pointing to our latest release.

That should be fixed now.

Can you please try again and let me know if not? 🙏

**Comment by afinetooth** [comment]
Actually, I'll clsoe this until I hear otherwise from you. Thanks.

**Comment by ConsoleCatzirl** [comment]
@afinetooth awesome! `v2` is working as expected now, thanks!

**Comment by afinetooth** [comment]
Perfect. Thanks for confirming!
