### ISSUE TITLE
Feature request: comment only on change

### ISSUE THREAD

**Issue by brianegge** [coverallsapp/github-action#235]
My PRs, such as updating github-actions, don't impact the coverage at all. It would be nice if coveralls could be configured to not comment when the there is no change in the code coverage.

**Comment by afinetooth** [comment]
Hi, @brianegge. 

That seems like a useful Repo Setting: 

- Don't send Status Checks / PR Comments when coverage is unchanged: ON/OFF

I have submitted that to our product team. 

Thanks for the request!
