### ISSUE TITLE
Coveralls isn't sending good names from github actions

### ISSUE THREAD

**Issue by eyal0** [coverallsapp/github-action#27]
When coveralls runs from TravisCI, it has reasonable looking identifiers that are set here:

https://github.com/coverallsapp/github-action/blob/master/node_modules/coveralls/lib/getOptions.js#L21

So, for example, the "service name" is "travis-ci" and that shows up in the coveralls output.  For github actions, it's always "GitHub".  And the message is always a merge commit instead of the actual commit that is being tested.

One solution might be to set environment variables correctly to trick the coveralls npm module to behave better.  For example, in the workflow, it might say:

```
env:
   TRAVIS: 1
   TRAVIS_JOB_ID: <get a better name here>
```

It might be possible to find better names than the defaults by looking at the checked out repo and also [environment variables](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables).

The better solution is to fix the coveralls npm module which this github action uses and modify it to recognize the eviroment.

Another good solution is to improve both this repo and the coveralls npm module to allow the user to specify those variables from the command line.  Then it could be set as arguments to this action and get passed all the way through coveralls to the coveralls server.

**Comment by nickmerwin** [comment]
Hi @eyal0, the newest version uses `GITHUB_RUN_ID` now instead of the commit SHA for the build number.
