### ISSUE TITLE
Merge pull request comments in parallel (matrix) building

### ISSUE THREAD

**Issue by peaceiris** [coverallsapp/github-action#33]
- When I run a matrix build with 3 platforms, 5 pull request comments will be added.
  - example pr: https://github.com/peaceiris/actions-mdbook/pull/39
- When I re-run jobs, comments will be added again.
  - example pr: https://github.com/peaceiris/actions-mdbook/pull/38

Are those behaviors expected?

**Comment by nickmerwin** [comment]
Hi @peaceiris, matrix builds are properly merged now in our updated version.

Example: https://github.com/coverallsapp/github-action#complete-parallel-job-example

**Comment by peaceiris** [comment]
Thanks!
