### ISSUE TITLE
No PR Comment when there is PR from forked repo

### ISSUE THREAD

**Issue by ibakshay** [coverallsapp/github-action#7]
Hi,

The Pull Request comment is not posted from Coveralls when there is a PR from the forked repository.  Could you please look into the issue ? 

Thanks in advance.

**Comment by Dunning-Kruger** [comment]
Same issue. Sample links:
- Pull request: https://github.com/OSDKDev/Panner.Order/pull/25    
- Workflow run: https://github.com/OSDKDev/Panner.Order/pull/25/checks?check_run_id=291306416  
- Job created in coveralls: https://coveralls.io/jobs/55335661

Yet... no comment or check is posted to the pull request.

**Comment by Dunning-Kruger** [comment]
@nickmerwin Any chance you could check this issue? It seems to me like a must-have for open source projects where work is done on forks and pull-requested in.

**Comment by a-b-r-o-w-n** [comment]
@Dunning-Kruger @ibakshay This is likely due to the fact that the github token is read-only for forked pull requests. https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token#permissions-for-the-github_token

**Comment by Dunning-Kruger** [comment]
@a-b-r-o-w-n Attempting to work-around this by creating a specific token and passing that to the action... do you know which permissions does coveralls require?

**Comment by a-b-r-o-w-n** [comment]
Github will not share any user secrets for forked repos. `${{ secrets.GITHUB_TOKEN }}` that is shared is a read-only token and cannot post PR comments. So there is no workaround as far as I know.

**Comment by bitsf** [comment]
I have the same problem, so this is the dead path right?
But why travis can post back comment?

**Comment by Can-Sahin** [comment]
So any open source projects using coveralls github actions cannot get their pull requests checked? Seems a big killer for me. Status check is stuck now
