### ISSUE TITLE
upgrade coveralls version to ^3.1.0

### ISSUE THREAD

**Issue by tkmct** [coverallsapp/github-action#76]
Hi, I recently used coveralls github-action for my project and faced an error below.
After a bit of research, it seems that the error is caused by coveralls package. And the error is fixed in the latest version.
Is it possible that someone kindly update to the latest version of coveralls?
It was little bit hard for me to update because when I tried to update using the latest version of npm, diff in package-lock.json seems huge. And I'm not familiar to the structure of the repo which does not ignore node_modules from source control.

Sincerely.

reference: https://github.com/nickmerwin/node-coveralls/issues/280

***
```
Error:  "2021-03-25T09:04:54.240Z"  'error from getOptions'
Error: Error: Command failed: git cat-file -p 9c10a1bb249f9d6bd9e92fa9f5ae2ed1a9137d3c
fatal: Not a valid object name 9c10a1bb249f9d6bd9e92fa9f5ae2ed1a9137d3c
```

**Comment by doong-jo** [comment]
@tkmct 
I met the same problem now. Can you share how you solved the problem?

**Comment by cyrus-za** [comment]
Same issue here and the github action does not use a locally installed package, right?
