### ISSUE TITLE
Bad response: 500 {"message":"Build processing error.","error":true,"url":""}

### ISSUE THREAD

**Issue by saulonunesdev** [coverallsapp/github-action#79]
Hi,

suddenly all PR are failing with

`Bad response: 500 {"message":"Build processing error.","error":true,"url":""}`

also, the github sign in page in https://coveralls.io/ is failing with `500`

i've checked the coveralls status but everything there is `operational`

![image](https://user-images.githubusercontent.com/26988193/116066310-4766fb00-a65e-11eb-94c7-0b32a42603b0.png)

**Comment by IraErshova** [comment]
Hi! We have the same issue

**Comment by saulonunesdev** [comment]
it's back thanks
